### ISSUE TITLE
Bug with the Coyote time

### ISSUE THREAD

**Issue by NightAttourney** [Ev01/PlatformerController2D#2]
I noticed when testing out the code that the coyote time doesn't work the way it's suppose to. You can actually set the coyote time to 0 run off the platform and still jump. I believe this is because of how the double jump is implemented. I tested this by creating a platform super high up and just walking off, and I still had the ability to jump with coyote time set to 0 and the number of jumps equal to 1. I also think the issues can be easier to see if you make the gravity multiplier and max_acceleration smaller. Basically I think due to how the double jump is implemented it allows for players to jump in the air twice which I don't think was intended.

I am also working to fix this issue myself, and I can screen record my project if you can't reproduce the bug on your end.

**Comment by Ev01** [comment]
Thanks for reporting this. It seemed this was because godot raised an error when setting the wait_time to 0 on the timer. I've fixed this by creating a `is_coyote_time_enabled` variable that sets itself to false if you set coyote_time to 0.
You will now have to use `start_coyote_timer()` instead of `coyote_timer.start()` and `is_coyote_timer_running()` instead of `not coyote_timer.is_stopped()`. These functions will check if the timer is enabled first before doing something with them. I've also done the same thing with the jump_buffer_timer since it had the same problem.

I've tested this solution and it seems to be working. Can you pull and make sure it works?
Also, I feel like this solution might be a bit hacky, so if you've found a simpler solution I'd be happy to implement that.

**Comment by NightAttourney** [comment]
Yes that fixed the issue from what I can tell. I actually think without fully rewriting the code the solution you implemented is the best that could be done, and I never even thought of that as a solution. Not sure what was causing it but the same issue happened even when coyote time was set to 1 or 10, but it now works the way it's suppose to. thank you for your great work!!

**Comment by Ev01** [comment]
Thanks!

**Comment by jnettl** [comment]
As far as I can see this is still an issue since this condition will always be true irrespective of the coyote timer - am I missing something here?

https://github.com/Ev01/PlatformerController2D/blob/1fcf58d14f4b951b5b6917099f235c94cdbb36d6/platformer_controller/platformer_controller.gd#L213-L215

It looks like checking if the player is on the ground would resolve that issue and allow the coyote timer to behave as intended.
```gd
func can_ground_jump() -> bool:
	if jumps_left > 0 and current_jump_type == JumpType.NONE and is_feet_on_ground():
		return true
```
